version: "3.9"

services:

    server:
        image: nginx
        ports: 
            - "8080:80"
#            - "app:5000"
        links:
            - app

    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
#        links:
 #           - "prometheus:9090"    

    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml

    node-exporter:
        image: bitnami/node-exporter
        ports:
            - "9100:9100"

    app:
        image: flask-app
        ports:
            - "5000:5000"
