version: "3.9"

services:

    server:
        image: nginx
        ports: 
            - "8080:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf

    grafana:
        image: grafana/grafana

    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml

    node-exporter:
        image: bitnami/node-exporter

    app:
        image: flask-app
